# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import customer_db_pb2 as customer__db__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in customer_db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerDBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/customerdbproto.CustomerDB/Register',
                request_serializer=customer__db__pb2.RegisterRequest.SerializeToString,
                response_deserializer=customer__db__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/customerdbproto.CustomerDB/Login',
                request_serializer=customer__db__pb2.LoginRequest.SerializeToString,
                response_deserializer=customer__db__pb2.UserResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/customerdbproto.CustomerDB/Logout',
                request_serializer=customer__db__pb2.UserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                _registered_method=True)
        self.ProductSearch = channel.unary_unary(
                '/customerdbproto.CustomerDB/ProductSearch',
                request_serializer=customer__db__pb2.ProductSearchRequest.SerializeToString,
                response_deserializer=customer__db__pb2.ProductSearchResponse.FromString,
                _registered_method=True)
        self.AddItemToCart = channel.unary_unary(
                '/customerdbproto.CustomerDB/AddItemToCart',
                request_serializer=customer__db__pb2.AddItemToCartRequest.SerializeToString,
                response_deserializer=customer__db__pb2.AddItemToCartResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/customerdbproto.CustomerDB/GetItem',
                request_serializer=customer__db__pb2.GetItemRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.RemoveItemFromCart = channel.unary_unary(
                '/customerdbproto.CustomerDB/RemoveItemFromCart',
                request_serializer=customer__db__pb2.RemoveItemFromCartRequest.SerializeToString,
                response_deserializer=customer__db__pb2.RemoveItemFromCartResponse.FromString,
                _registered_method=True)
        self.SaveCart = channel.unary_unary(
                '/customerdbproto.CustomerDB/SaveCart',
                request_serializer=customer__db__pb2.UserRequest.SerializeToString,
                response_deserializer=customer__db__pb2.SaveCartResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/customerdbproto.CustomerDB/ClearCart',
                request_serializer=customer__db__pb2.UserRequest.SerializeToString,
                response_deserializer=customer__db__pb2.ClearCartResponse.FromString,
                _registered_method=True)
        self.DisplayCart = channel.unary_unary(
                '/customerdbproto.CustomerDB/DisplayCart',
                request_serializer=customer__db__pb2.UserRequest.SerializeToString,
                response_deserializer=customer__db__pb2.DisplayCartResponse.FromString,
                _registered_method=True)
        self.ProvideFeedback = channel.unary_unary(
                '/customerdbproto.CustomerDB/ProvideFeedback',
                request_serializer=customer__db__pb2.ProvideFeedbackRequest.SerializeToString,
                response_deserializer=customer__db__pb2.ProvideFeedbackResponse.FromString,
                _registered_method=True)
        self.GetSellerRating = channel.unary_unary(
                '/customerdbproto.CustomerDB/GetSellerRating',
                request_serializer=customer__db__pb2.GetSellerRatingRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GetSellerRatingResponse.FromString,
                _registered_method=True)
        self.GetBuyerPurchases = channel.unary_unary(
                '/customerdbproto.CustomerDB/GetBuyerPurchases',
                request_serializer=customer__db__pb2.UserRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GetBuyerPurchasesResponse.FromString,
                _registered_method=True)


class CustomerDBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Registers the user for the service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Logins the user for the service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logsout the user for the service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProductSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItemToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveItemFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerPurchases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=customer__db__pb2.RegisterRequest.FromString,
                    response_serializer=customer__db__pb2.RegisterResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=customer__db__pb2.LoginRequest.FromString,
                    response_serializer=customer__db__pb2.UserResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=customer__db__pb2.UserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'ProductSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.ProductSearch,
                    request_deserializer=customer__db__pb2.ProductSearchRequest.FromString,
                    response_serializer=customer__db__pb2.ProductSearchResponse.SerializeToString,
            ),
            'AddItemToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItemToCart,
                    request_deserializer=customer__db__pb2.AddItemToCartRequest.FromString,
                    response_serializer=customer__db__pb2.AddItemToCartResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=customer__db__pb2.GetItemRequest.FromString,
                    response_serializer=customer__db__pb2.GetItemResponse.SerializeToString,
            ),
            'RemoveItemFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveItemFromCart,
                    request_deserializer=customer__db__pb2.RemoveItemFromCartRequest.FromString,
                    response_serializer=customer__db__pb2.RemoveItemFromCartResponse.SerializeToString,
            ),
            'SaveCart': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCart,
                    request_deserializer=customer__db__pb2.UserRequest.FromString,
                    response_serializer=customer__db__pb2.SaveCartResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=customer__db__pb2.UserRequest.FromString,
                    response_serializer=customer__db__pb2.ClearCartResponse.SerializeToString,
            ),
            'DisplayCart': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayCart,
                    request_deserializer=customer__db__pb2.UserRequest.FromString,
                    response_serializer=customer__db__pb2.DisplayCartResponse.SerializeToString,
            ),
            'ProvideFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideFeedback,
                    request_deserializer=customer__db__pb2.ProvideFeedbackRequest.FromString,
                    response_serializer=customer__db__pb2.ProvideFeedbackResponse.SerializeToString,
            ),
            'GetSellerRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRating,
                    request_deserializer=customer__db__pb2.GetSellerRatingRequest.FromString,
                    response_serializer=customer__db__pb2.GetSellerRatingResponse.SerializeToString,
            ),
            'GetBuyerPurchases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerPurchases,
                    request_deserializer=customer__db__pb2.UserRequest.FromString,
                    response_serializer=customer__db__pb2.GetBuyerPurchasesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customerdbproto.CustomerDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('customerdbproto.CustomerDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerDB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/Register',
            customer__db__pb2.RegisterRequest.SerializeToString,
            customer__db__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/Login',
            customer__db__pb2.LoginRequest.SerializeToString,
            customer__db__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/Logout',
            customer__db__pb2.UserRequest.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProductSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/ProductSearch',
            customer__db__pb2.ProductSearchRequest.SerializeToString,
            customer__db__pb2.ProductSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItemToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/AddItemToCart',
            customer__db__pb2.AddItemToCartRequest.SerializeToString,
            customer__db__pb2.AddItemToCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/GetItem',
            customer__db__pb2.GetItemRequest.SerializeToString,
            customer__db__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveItemFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/RemoveItemFromCart',
            customer__db__pb2.RemoveItemFromCartRequest.SerializeToString,
            customer__db__pb2.RemoveItemFromCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/SaveCart',
            customer__db__pb2.UserRequest.SerializeToString,
            customer__db__pb2.SaveCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/ClearCart',
            customer__db__pb2.UserRequest.SerializeToString,
            customer__db__pb2.ClearCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisplayCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/DisplayCart',
            customer__db__pb2.UserRequest.SerializeToString,
            customer__db__pb2.DisplayCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvideFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/ProvideFeedback',
            customer__db__pb2.ProvideFeedbackRequest.SerializeToString,
            customer__db__pb2.ProvideFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/GetSellerRating',
            customer__db__pb2.GetSellerRatingRequest.SerializeToString,
            customer__db__pb2.GetSellerRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerPurchases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customerdbproto.CustomerDB/GetBuyerPurchases',
            customer__db__pb2.UserRequest.SerializeToString,
            customer__db__pb2.GetBuyerPurchasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
