# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_stubs.customer_db_pb2 as customer__db__pb2


class CustomerDBStub(object):
    """General Customer DB service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/customerdbproto.CustomerDB/Register',
                request_serializer=customer__db__pb2.RegisterRequest.SerializeToString,
                response_deserializer=customer__db__pb2.RegisterResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/customerdbproto.CustomerDB/Login',
                request_serializer=customer__db__pb2.LoginRequest.SerializeToString,
                response_deserializer=customer__db__pb2.UserResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/customerdbproto.CustomerDB/Logout',
                request_serializer=customer__db__pb2.LogoutRequest.SerializeToString,
                response_deserializer=customer__db__pb2.UserResponse.FromString,
                )
        self.GetSellerRating = channel.unary_unary(
                '/customerdbproto.CustomerDB/GetSellerRating',
                request_serializer=customer__db__pb2.GetSellerRatingRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GetSellerRatingResponse.FromString,
                )


class CustomerDBServicer(object):
    """General Customer DB service
    """

    def Register(self, request, context):
        """Registers the user for the service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Logins the user for the service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logout the user for the service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRating(self, request, context):
        """method to get seller rating
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=customer__db__pb2.RegisterRequest.FromString,
                    response_serializer=customer__db__pb2.RegisterResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=customer__db__pb2.LoginRequest.FromString,
                    response_serializer=customer__db__pb2.UserResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=customer__db__pb2.LogoutRequest.FromString,
                    response_serializer=customer__db__pb2.UserResponse.SerializeToString,
            ),
            'GetSellerRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRating,
                    request_deserializer=customer__db__pb2.GetSellerRatingRequest.FromString,
                    response_serializer=customer__db__pb2.GetSellerRatingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customerdbproto.CustomerDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CustomerDB(object):
    """General Customer DB service
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customerdbproto.CustomerDB/Register',
            customer__db__pb2.RegisterRequest.SerializeToString,
            customer__db__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customerdbproto.CustomerDB/Login',
            customer__db__pb2.LoginRequest.SerializeToString,
            customer__db__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customerdbproto.CustomerDB/Logout',
            customer__db__pb2.LogoutRequest.SerializeToString,
            customer__db__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSellerRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customerdbproto.CustomerDB/GetSellerRating',
            customer__db__pb2.GetSellerRatingRequest.SerializeToString,
            customer__db__pb2.GetSellerRatingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
