# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_struct.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import grpc_stubs.customer_db_pb2 as customer__db__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14message_struct.proto\x1a\x11\x63ustomer_db.proto\"x\n\x0eGeneralMessage\x12*\n\x0frequest_message\x18\x01 \x01(\x0b\x32\x0f.RequestMessageH\x00\x12*\n\x0fservice_message\x18\x02 \x01(\x0b\x32\x0f.ServiceMessageH\x00\x42\x0e\n\x0cmessage_type\"\xe9\x01\n\x0eRequestMessage\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x1a\n\x12local_sequence_num\x18\x02 \x01(\x05\x12\x36\n\rlogin_request\x18\x03 \x01(\x0b\x32\x1d.customerdbproto.LoginRequestH\x00\x12<\n\x10register_request\x18\x04 \x01(\x0b\x32 .customerdbproto.RegisterRequestH\x00\x12\"\n\x08metadata\x18\x05 \x01(\x0b\x32\x10.RequestMetadataB\x0e\n\x0crequest_body\"*\n\x0fRequestMetadata\x12\x17\n\x0fglobal_sequence\x18\x01 \x01(\x05\"\x81\x01\n\x0eServiceMessage\x12\x11\n\tsource_id\x18\x01 \x01(\x05\x12\x12\n\nrequest_id\x18\x02 \x01(\x05\x12\x11\n\tglobal_id\x18\x03 \x01(\x05\x12\x11\n\tsender_id\x18\x04 \x01(\x05\x12\"\n\x08metadata\x18\x05 \x01(\x0b\x32\x10.ServiceMetadata\"-\n\x0fServiceMetadata\x12\x1a\n\x12last_delivered_seq\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_struct_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GENERALMESSAGE']._serialized_start=43
  _globals['_GENERALMESSAGE']._serialized_end=163
  _globals['_REQUESTMESSAGE']._serialized_start=166
  _globals['_REQUESTMESSAGE']._serialized_end=399
  _globals['_REQUESTMETADATA']._serialized_start=401
  _globals['_REQUESTMETADATA']._serialized_end=443
  _globals['_SERVICEMESSAGE']._serialized_start=446
  _globals['_SERVICEMESSAGE']._serialized_end=575
  _globals['_SERVICEMETADATA']._serialized_start=577
  _globals['_SERVICEMETADATA']._serialized_end=622
# @@protoc_insertion_point(module_scope)
